# This is a basic workflow to help you get started with Actions

name: Simple Test for Private Repos 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "moodle-403-testing-gha-with-private-repo" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Runs a set of commands to debug submodule checkouts
      - name: Debugging for submodules
        run: |
          echo Run ls -alR admin/tool/ucsfsomapi 
          ls -alR admin/tool/ucsfsomapi
          echo Run cat .gitmodules
          cat .gitmodules
